### PR TITLE
rename readme file and package.json file

### PR DESCRIPTION
**Pull request by gtrmonkey**
## Related Issue
Resolve Issue #3 

## Summary of Changes
Renamed Readme to add the repo name and added the repo title to package .json

### CODE REVIEW

**Comment by thescientist13** [comment]
oh, sorry for the confusion @gtrmonkey but the change request I had in mind was to update the project name in both of those files, not the file names themselves.

so from _lambda-topology-ingest_ -> _lambda-topology_

If you want to make that change and undo the other ones, that would be great!  🙏

**Comment by gtrmonkey** [comment]
Did you want me to update this too in the json file also to the current
repo link  "repository": "git@github.com:
ContributaryCommunity/lambda-topology-ingest.git",

**Comment by gtrmonkey** [comment]
I have already made un did the changes I made and I have believe I have
done them correctly now

**Comment by thescientist13** [comment]
Thanks! You might want to do a find / replace.  There are a few more instances in each file.  👍

**Comment by gtrmonkey** [comment]
Do you want me to update everything that says  *lambda-topology-ingest* to
*lambda-topology? *

**Comment by gtrmonkey** [comment]
for example in some of the links have ingest also your repo url still has
ingest. sorry I am pretty new at this and trying to do this for correctly

**Comment by thescientist13** [comment]
> Do you want me to update everything that says  *lambda-topology-ingest* to
*lambda-topology? *

Correct.  I would like to update all instances / usages.

If I do a search in the README.md for example, I'll see there are 11 usages in total that would need to made
screen shot 2018-11-02 at 7 38 34 am

In _package.json_ there are two
screen shot 2018-11-02 at 7 39 51 am

Thanks for your help, don't worry about the build error, it seems unrelated to these changes here so I will take a look on my end.   Changing the actual GitHub repo URL through GitHub I will do myself after we land this PR.

Let me know if you have any other questions!

**Comment by thescientist13** [comment]
@gtrmonkey 
Awesome, looks great!  Let me see if I can resolve the build error and then this good to go!  🎉

**Comment by thescientist13** [comment]
@gtrmonkey 
Identified the issue, should have this all set in a few.
https://github.com/ContributaryCommunity/lambda-topology-ingest/issues/5

**Review by thescientist13 — APPROVED** [review]
Thanks so much @gtrmonkey , all set now!  👏

**Comment by gtrmonkey** [comment]
Thank you too, for this great experince. :D

**Pull request merged**
